name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "${GITHUB_ENV}"

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

  publish-gem:
    name: Publish Gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: ActionsToolbox/gem-release-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - create-release
      - publish-gem
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
